version: '3'
services:
  neo4j:
    image: neo4j:latest
    restart: unless-stopped
    ports:
      - 7474:7474
    environment:
      # Raise memory limits
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
      # Disable authentication
      - NEO4J_AUTH=none

  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    depends_on:
      - neo4j
    ports:
      - 8000:8000
    networks:
      - app

  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - 8080: 8080
    networks:
      - app

networks:
  app: